interface DesignerContext {
  product_description: string;
  design_tools?: string[];
  design_system: string;
  tech_stack: string[];
  experience_level: string;
  tone_preference?: string;
}

export function generateClaudeMd(ctx: DesignerContext): string {
  const experienceGuide: Record<string, string> = {
    beginner:
      "This designer is a beginner. Explain everything in plain language. Avoid jargon. Use Figma analogies when possible. Show one step at a time and confirm before moving on.",
    intermediate:
      "This designer has intermediate experience. They can follow technical instructions but appreciate clear context on why things work. Don't over-explain basics but don't assume deep knowledge of edge cases.",
    advanced:
      "This designer is advanced. Keep explanations concise and technical. They want direct answers and specific implementation details, not hand-holding.",
  };

  const toneGuide: Record<string, string> = {
    concise:
      "Keep responses short and direct. Skip preamble. Use bullet lists over prose when possible.",
    explanatory:
      "Explain the reasoning behind design choices. Connect decisions back to user experience and industry patterns they'd recognise.",
    encouraging:
      "Be warm and confidence-building. Acknowledge progress. Reframe obstacles as normal steps in the process.",
  };

  const designSystemNote = ctx.design_system === "None yet"
    ? "No design system yet. Suggest Tailwind CSS as a starting point and offer to set up design tokens."
    : `Uses ${ctx.design_system}. Respect their existing design system in all suggestions.`;

  return `# Project CLAUDE.md
# Generated by Design with Claude

## About this designer
- **Experience level:** ${ctx.experience_level}
- **Design tools:** ${(ctx.design_tools ?? ["Figma"]).join(", ")}
- **Design system:** ${ctx.design_system}
- **Tech stack:** ${ctx.tech_stack.join(", ")}
- **Tone preference:** ${ctx.tone_preference ?? "explanatory"}

## What they're building
${ctx.product_description}

## How to communicate
${experienceGuide[ctx.experience_level] || experienceGuide.beginner}

${ctx.tone_preference ? toneGuide[ctx.tone_preference] ?? "" : ""}

## Design system
${designSystemNote}

## Rules
- Always think about the design implications before writing code
- Suggest design tokens (colors, spacing, typography) before component implementation
- When generating UI, follow accessibility best practices (WCAG 2.1 AA)
- Use semantic HTML elements
- Explain design decisions in terms of user experience, not just technical implementation
- When the designer asks about a pattern, reference real-world examples they'd recognize
- Never assume they know terminal commands — show the exact command to run
- If they're stuck on a technical wall (deployment, database, auth), guide them through it step by step
`;
}
