// Writes the full findings report to `.dwic/audit-<YYYY-MM-DD>.md`. The
// dashboard output is scannable; this file is shareable / commit-able.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CATEGORY_LABELS, type CategoryResult } from "./aggregator.js";
import type { DetectedProjectConfig } from "../utils/detect-project-config.js";

function todayStamp(): string {
  const d = new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function renderCategory(r: CategoryResult): string {
  const parts: string[] = [];
  parts.push(`## ${CATEGORY_LABELS[r.category]} — ${r.severity}`);
  parts.push("");
  parts.push(`_${r.gist}_`);
  parts.push("");
  if (r.findings.length === 0) {
    parts.push("No findings in this pass.");
    parts.push("");
    return parts.join("\n");
  }
  const byLevel: Record<"error" | "warn" | "info", typeof r.findings> = { error: [], warn: [], info: [] };
  for (const f of r.findings) byLevel[f.severity].push(f);
  for (const level of ["error", "warn", "info"] as const) {
    if (byLevel[level].length === 0) continue;
    const icon = level === "error" ? "✗" : level === "warn" ? "⚠" : "·";
    parts.push(`### ${icon} ${level.toUpperCase()}`);
    parts.push("");
    for (const f of byLevel[level]) {
      const tag = f.token ? `\`${f.token}\`` : f.element ? `\`${f.element}\`` : "";
      parts.push(`- ${tag ? `${tag} — ` : ""}${f.message}`);
    }
    parts.push("");
  }
  return parts.join("\n");
}

const CATEGORY_TO_TOOL: Record<CategoryResult["category"], string> = {
  color: "color-specialist",
  typography: "typography-specialist",
  spacing: "spacing-specialist",
  accessibility: "accessibility-specialist",
  form: "form-designer",
  navigation: "navigation-specialist",
  motion: "motion-designer",
  copy: "content-strategist",
};

export interface WrittenReport {
  path: string;
  relativePath: string;
}

export function writeMarkdownReport(
  cwd: string,
  detected: DetectedProjectConfig,
  results: CategoryResult[],
): WrittenReport {
  const dir = join(cwd, ".dwic");
  mkdirSync(dir, { recursive: true });
  const stamp = todayStamp();
  const path = join(dir, `audit-${stamp}.md`);
  const totalErr = results.reduce((a, r) => a + r.counts.error, 0);
  const totalWarn = results.reduce((a, r) => a + r.counts.warn, 0);
  const totalInfo = results.reduce((a, r) => a + r.counts.info, 0);

  const header: string[] = [
    `# dwic audit — ${stamp}`,
    "",
    `- **Framework:** ${detected.framework}${detected.frameworkVersion ? ` ${detected.frameworkVersion}` : ""}`,
    `- **Tech stack:** ${detected.techStack.length ? detected.techStack.join(", ") : "unknown"}`,
    `- **Findings:** ${totalErr} error(s), ${totalWarn} warning(s), ${totalInfo} info`,
    `- **Generated by:** [dwic](https://designwithclaude.com)`,
    "",
    "---",
    "",
  ];

  const body = results.map(renderCategory).join("---\n\n");

  const followUps = results
    .filter((r) => r.severity === "error" || r.severity === "warn")
    .map((r) => `- Run \`${CATEGORY_TO_TOOL[r.category]}\` with \`mode:"audit"\` inside Claude Code — ${r.gist}`);

  const footer = [
    "---",
    "",
    "## Next steps",
    "",
    followUps.length > 0 ? followUps.join("\n") : "System looks consistent on static analysis — schedule a live QA pass.",
    "",
    "## How this report was made",
    "",
    `Ran \`dwic audit\` at the repo root on ${stamp}. Every finding above was computed by a static analyser; no LLM ran. The same audit logic runs inside Claude Code via the dwic MCP server — install it with \`npx @imrandwc/dwic setup\` to run the specialists interactively.`,
    "",
  ].join("\n");

  const full = header.join("\n") + body + footer;
  writeFileSync(path, full, "utf8");
  return { path, relativePath: `.dwic/audit-${stamp}.md` };
}
