import { z } from "zod";
import { defineTool } from "./types.js";
import { composeRolePrompt } from "./loadPrompt.js";
import { buildNeutralRamp, buildPrimaryRamp, buildSemanticColors } from "./color.js";
import type { PaletteData } from "./types.js";

const DEFAULT_ACCENT = "#5B8DEF";

function buildSeedPalette(accentHex: string, name: string): PaletteData {
  const primary = buildPrimaryRamp(accentHex);
  const neutral = buildNeutralRamp(accentHex);
  const semantic = buildSemanticColors();
  const tokens: PaletteData["tokens"] = [
    ...primary.map((p) => ({
      name: `--color-primary-${p.step}`,
      hex: p.hex,
      role: p.step === 500 ? "primary base" : `primary ${p.step}`,
    })),
    ...neutral.map((n) => ({
      name: `--color-neutral-${n.step}`,
      hex: n.hex,
      role: n.step === 500 ? "neutral base" : `neutral ${n.step}`,
    })),
    ...semantic.map((s) => ({
      name: `--color-${s.role}`,
      hex: s.hex,
      role: s.role,
    })),
  ];
  return { name, tokens };
}

export const colorSpecialistTool = defineTool({
  name: "color-specialist",
  title: "Color Specialist",
  description:
    "Generates accessibility-checked color palettes: primary + neutral ramps, semantic colors, and CSS token names. Pass an accent hex if the designer has one; otherwise the tool picks a neutral starting accent and the model refines from the brief.",
  inputSchema: {
    brief: z
      .string()
      .min(1)
      .describe("Describe the product, mood, and any color constraints."),
    accent: z
      .string()
      .optional()
      .describe(
        "Optional accent color as hex (e.g. '#5B8DEF'). If omitted, a neutral default is used.",
      ),
    mode: z
      .enum(["light", "dark", "both"])
      .optional()
      .describe("Output target. Defaults to 'both'."),
  },
  outputKind: "palette",
  handler: ({ brief, accent, mode }) => {
    const accentHex = accent?.trim() || DEFAULT_ACCENT;
    const paletteName = `palette-${accentHex.replace("#", "").slice(0, 6)}`;
    const palette = buildSeedPalette(accentHex, paletteName);

    const seedTable = palette.tokens
      .map((t) => `- \`${t.name}\` · ${t.hex} · ${t.role}`)
      .join("\n");

    const text = composeRolePrompt({
      roleName: "Color Specialist",
      commandFile: "color-specialist.md",
      sections: [
        { heading: "Designer's brief", body: brief },
        { heading: "Target mode", body: mode ?? "both" },
        { heading: "Accent", body: accentHex === DEFAULT_ACCENT ? "not provided — using default #5B8DEF" : accentHex },
        {
          heading: "Seed palette (generated by the MCP server)",
          body: `${seedTable}\n\nThis is a deterministic starting point. Refine against the brief — especially contrast ratios for body text and button states.`,
        },
      ],
      closingInstruction:
        "Respond with a refined palette. For each token: name, hex, intended role, and which surface/text pairings meet WCAG AA (4.5:1). Call out any accessibility issues in the seed. If the brief implies a mood (calm, urgent, premium), justify the primary hue choice.",
    });

    return {
      text,
      output: { type: "palette", data: palette },
    };
  },
});
