import { z } from "zod";
import { defineTool, type SpacingData } from "./types.js";
import { composeRolePrompt } from "./loadPrompt.js";

const DEFAULT_BASE = 4;
const STEPS = [
  { name: "0", multiplier: 0 },
  { name: "0.5", multiplier: 0.5 },
  { name: "1", multiplier: 1 },
  { name: "2", multiplier: 2 },
  { name: "3", multiplier: 3 },
  { name: "4", multiplier: 4 },
  { name: "5", multiplier: 6 },
  { name: "6", multiplier: 8 },
  { name: "7", multiplier: 12 },
  { name: "8", multiplier: 16 },
  { name: "9", multiplier: 24 },
  { name: "10", multiplier: 32 },
];

function buildSpacingScale(basePx: number, name: string): SpacingData {
  return {
    name,
    steps: STEPS.map((s) => {
      const px = basePx * s.multiplier;
      return {
        name: `space-${s.name}`,
        px,
        rem: +(px / 16).toFixed(4),
      };
    }),
  };
}

export const spacingSpecialistTool = defineTool({
  name: "spacing-specialist",
  title: "Spacing & Layout Specialist",
  description:
    "Generates a spacing scale and basic layout/grid rhythm. Output is a token list the designer can drop into Tailwind, CSS vars, or Figma tokens. The model refines based on density intent (compact vs generous).",
  inputSchema: {
    brief: z
      .string()
      .min(1)
      .describe("Product + density intent. Dashboard? Marketing? Forms-heavy?"),
    baseUnitPx: z
      .number()
      .optional()
      .describe("Base unit in px. Default 4."),
  },
  outputKind: "spacing",
  handler: ({ brief, baseUnitPx }) => {
    const base = baseUnitPx ?? DEFAULT_BASE;
    const scale = buildSpacingScale(base, `spacing-${base}px`);

    const table = scale.steps
      .map((s) => `- \`--${s.name}\` · ${s.px}px · ${s.rem}rem`)
      .join("\n");

    const text = composeRolePrompt({
      roleName: "Spacing & Layout Specialist",
      commandFile: "spacing-layout-specialist.md",
      sections: [
        { heading: "Designer's brief", body: brief },
        { heading: "Base unit", body: `${base}px` },
        {
          heading: "Seed spacing scale (generated by the MCP server)",
          body: `${table}\n\nNon-linear steps (0.5, 1, 2, 3, 4, 6, 8, 12, 16, 24, 32) to preserve rhythm without bloat. Adjust density to match the brief.`,
        },
      ],
      closingInstruction:
        "Respond with: (1) recommended spacing tokens and when to use each, (2) grid / container widths, (3) section padding presets (compact/default/generous), (4) component-level conventions (card, button, input padding).",
    });

    return {
      text,
      output: { type: "spacing", data: scale },
    };
  },
});
