import { z } from "zod";
import { defineTool, type TypeScaleData } from "./types.js";
import { composeRolePrompt } from "./loadPrompt.js";

const DEFAULT_BASE = 16;
const DEFAULT_RATIO = 1.25; // major third — comfortable for UI

interface ScaleStep {
  role: string;
  weight: number;
  lineHeight: number | string;
  scaleFactor: number;
}

const STEPS: ScaleStep[] = [
  { role: "display", weight: 700, lineHeight: 1.05, scaleFactor: 4 },
  { role: "h1", weight: 700, lineHeight: 1.1, scaleFactor: 3 },
  { role: "h2", weight: 600, lineHeight: 1.15, scaleFactor: 2.25 },
  { role: "h3", weight: 600, lineHeight: 1.2, scaleFactor: 1.6 },
  { role: "h4", weight: 600, lineHeight: 1.3, scaleFactor: 1.25 },
  { role: "body-lg", weight: 400, lineHeight: 1.5, scaleFactor: 1.125 },
  { role: "body", weight: 400, lineHeight: 1.55, scaleFactor: 1 },
  { role: "body-sm", weight: 400, lineHeight: 1.5, scaleFactor: 0.875 },
  { role: "caption", weight: 500, lineHeight: 1.4, scaleFactor: 0.75 },
];

function clampForStep(basePx: number, scaleFactor: number): string {
  const minPx = Math.max(12, basePx * scaleFactor * 0.875);
  const maxPx = basePx * scaleFactor;
  const preferredVw = +(maxPx / 16 / 8).toFixed(3);
  const minRem = +(minPx / 16).toFixed(3);
  const maxRem = +(maxPx / 16).toFixed(3);
  return `clamp(${minRem}rem, ${minRem}rem + ${preferredVw}vw, ${maxRem}rem)`;
}

function buildTypeScale(basePx: number, ratio: number, name: string): TypeScaleData {
  return {
    name,
    scale: STEPS.map((step) => {
      // Apply ratio-scaled lightness for more even tonal change
      const factor = step.scaleFactor === 1 ? 1 : step.scaleFactor * (ratio / DEFAULT_RATIO);
      return {
        role: step.role,
        clamp: clampForStep(basePx, factor),
        lineHeight: step.lineHeight,
        weight: step.weight,
      };
    }),
  };
}

export const typographySpecialistTool = defineTool({
  name: "typography-specialist",
  title: "Typography Specialist",
  description:
    "Generates a fluid type scale with clamp() values, line-heights, and weights. Output is a working scale for body + headings; the model refines per the brief (e.g., editorial vs utilitarian).",
  inputSchema: {
    brief: z
      .string()
      .min(1)
      .describe("Product + tone. Editorial? Utilitarian? Tight or generous?"),
    baseSizePx: z
      .number()
      .optional()
      .describe("Base body size in px. Default 16."),
    ratio: z
      .number()
      .optional()
      .describe("Modular scale ratio. Default 1.25 (major third)."),
  },
  outputKind: "type-scale",
  handler: ({ brief, baseSizePx, ratio }) => {
    const base = baseSizePx ?? DEFAULT_BASE;
    const r = ratio ?? DEFAULT_RATIO;
    const scale = buildTypeScale(base, r, `type-scale-${base}-${r}`);

    const scaleTable = scale.scale
      .map(
        (s) =>
          `- \`${s.role}\` · ${s.clamp} · weight ${s.weight} · line-height ${s.lineHeight}`,
      )
      .join("\n");

    const text = composeRolePrompt({
      roleName: "Typography Specialist",
      commandFile: "typography-specialist.md",
      sections: [
        { heading: "Designer's brief", body: brief },
        { heading: "Base size", body: `${base}px` },
        { heading: "Modular ratio", body: `${r}` },
        {
          heading: "Seed type scale (generated by the MCP server)",
          body: `${scaleTable}\n\nAll sizes use clamp() for fluid scaling. Adjust if the brief wants tighter or looser hierarchy.`,
        },
      ],
      closingInstruction:
        "Respond with a refined type system: font family recommendation(s), pairings, when to use each role, and any vertical-rhythm adjustments. Keep body line-height in the 1.5–1.65 range for readability unless the brief overrides.",
    });

    return {
      text,
      output: { type: "type-scale", data: scale },
    };
  },
});
